# Netlify background deploy script generated by Copilot
$envFile = 'D:\A11\.env.netlify'
if (-not (Test-Path $envFile)) {
  Write-Output 'Missing .env.netlify'
  exit 2
}
Get-Content $envFile | ForEach-Object {
  if ($_ -match '^\s*([^#=]+)\s*=(.*)$') {
    $k = $matches[1].Trim()
    $v = $matches[2].Trim()
    $v = $v.Trim('"')
    $v = $v.Trim("'")
    Set-Item -Path "Env:\$k" -Value $v
  }
}

Set-Location -Path 'D:\A11\apps\web'
Write-Output "[deploy] npm ci start"
npm ci --no-audit --no-fund
Write-Output "[deploy] npm run build start"
npm run build
Write-Output "[deploy] netlify deploy start"
npx --yes netlify deploy --dir dist --prod --site $env:NETLIFY_SITE_ID --auth $env:NETLIFY_AUTH_TOKEN -m 'Automated deploy from Copilot'
